wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      Bounding Box Debugger/Images_wandb_delimeter_predictions:
        key: Bounding Box Debugger/Images_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': person
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1676671488.280659
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 13
      - 16
      - 19
      - 23
      4: 3.8.13
      5: 0.13.3
      8:
      - 2
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 16
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
cfg:
  desc: null
  value: cfg/yolov7-tiny-pose.yaml
data:
  desc: null
  value: data/coco_kpts_local.yaml
data_dict:
  desc: null
  value:
    names:
    - person
    nc: 1
    test: /home/shackleford/data/coco2017labels-keypoints/test2017.txt
    train: /home/shackleford/data/coco2017labels-keypoints/train2017.txt
    val: /home/shackleford/data/coco2017labels-keypoints/val2017.txt
device:
  desc: null
  value: '0'
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 300
evolve:
  desc: null
  value: false
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value: 0
global_rank:
  desc: null
  value: -1
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.3
    cls_pw: 1.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.0
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    kpt: 0.1
    lr0: 0.01
    lrf: 0.1
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 0.7
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
img_size:
  desc: null
  value:
  - 640
  - 640
kpt_label:
  desc: null
  value: 'true'
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: tiny
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
opt:
  desc: null
  value:
    adam: false
    artifact_alias: latest
    batch_size: 16
    bbox_interval: -1
    bucket: ''
    cache_images: false
    cfg: cfg/yolov7-tiny-pose.yaml
    data: data/coco_kpts_local.yaml
    device: '0'
    entity: null
    epochs: 300
    evolve: false
    exist_ok: false
    freeze: 0
    global_rank: -1
    hyp:
      anchor_t: 4.0
      box: 0.05
      cls: 0.3
      cls_pw: 1.0
      degrees: 0.0
      fl_gamma: 0.0
      fliplr: 0.0
      flipud: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      iou_t: 0.2
      kpt: 0.1
      lr0: 0.01
      lrf: 0.1
      mixup: 0.0
      momentum: 0.937
      mosaic: 1.0
      obj: 0.7
      obj_pw: 1.0
      perspective: 0.0
      scale: 0.5
      shear: 0.0
      translate: 0.1
      warmup_bias_lr: 0.1
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      weight_decay: 0.0005
    image_weights: false
    img_size:
    - 640
    - 640
    kpt_label: 'true'
    label_smoothing: 0.0
    linear_lr: false
    local_rank: -1
    multi_scale: false
    name: tiny
    noautoanchor: false
    nosave: false
    notest: false
    project: runs/train
    quad: false
    rect: false
    resume: false
    save_dir: runs/train/tiny
    save_period: -1
    single_cls: false
    sync_bn: 'true'
    total_batch_size: 16
    upload_dataset: false
    weights: ../yolov7-tiny.pt
    workers: 8
    world_size: 1
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/tiny
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: 'true'
total_batch_size:
  desc: null
  value: 16
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: ../yolov7-tiny.pt
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: 1
